services:
  jekyll:
    build: docs/
    labels:
      caddy: "faros.${DOCKER_HOST_SUFFIX}"
      caddy.tls: internal
      caddy.reverse_proxy: "{{ upstreams }}"
    networks:
      - public
    volumes:
      - ./docs/:/usr/src/app/
    working_dir: /usr/src/app

networks:
  public:
    external: true
    name: dev_public
