version:  '3'

networks:
    proxy:
        external:
            name: dev_proxy

services:
    jekyll:
        image: jekyll/jekyll:3.8
        volumes:
            - .:/srv/jekyll
            - ./vendor/bundle:/usr/local/bundle
        command: jekyll serve
        ports:
            - 4000:4000
        expose:
            - 4000
        networks:
            - proxy
        environment:
            VIRTUAL_HOST: faros.$DOCKER_HOST_SUFFIX
            VIRTUAL_PORT: 4000
